[package]
name = "engine-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["http2", "multipart", "ws"] }
base64 = "0.23.1"
chrono = "0.4.45"
hex = "0.4.3"
hmac = "0.13.0"
sea-orm = { version = "2.0.1", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "debug-print",
    "mock",
    "schema-sync",
    "entity-registry",
    "with-json",
    "sqlx-postgres",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
thiserror = "2.0.19"
uuid = { version = "1.24.0", features = ["v7", "serde"] }

[dev-dependencies]
log = "0.4.33"
testcontainers-modules = { version = "0.15.0", features = [
    "postgres",
    "valkey",
] }
tokio = { version = "1.53.1", features = ["full"] }
tower = { version = "0.5.3", features = ["util"] }
